package com.stono.mybatis.test;

import com.stono.mybatis.bean.Department;
import com.stono.mybatis.bean.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.DEPARTMENT
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByPrimaryKey(Department record);
}