package com.stono.mybatis.test;

import com.stono.mybatis.bean.Person;
import com.stono.mybatis.bean.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGA1.PERSON
     *
     * @mbggenerated Tue Dec 30 10:34:26 CST 2014
     */
    int updateByPrimaryKey(Person record);
}